### ISSUE TITLE
can't find the way of sampling

### ISSUE THREAD

**Issue by Zhu-811** [huangtinglin/MixGCF#1]
are there all the sampling methods mentioned in the paper? I only found the way of RNS.

**Comment by huangtinglin** [comment]
Hi. Thanks for your attention. Here is the implementation of MixGCF:

1. https://github.com/huangtinglin/MixGCF/blob/main/modules/LightGCN.py#L138
2. https://github.com/huangtinglin/MixGCF/blob/main/modules/NGCF.py#L157

**Comment by Zhu-811** [comment]
thanks
