### ISSUE TITLE
The verification process is extremely time consuming

### ISSUE THREAD

**Issue by Wjk666** [huangtinglin/MixGCF#2]
Is exists any better implementation?

**Comment by huangtinglin** [comment]
Thanks for your attention! We conduct the all-ranking strategy in the evaluation process. That is, for each user, all the items which do not occur in training set will be ranked based on the predictions of the model. So it is time-consuming for some datasets with a large number of users, e.g., Amazon. Here are some simple tricks to accelerate the evaluation process:

1. Stop the evaluate performance in the testing set (https://github.com/huangtinglin/MixGCF/blob/main/main.py#L133).
2. Increase the testing batchsize (https://github.com/huangtinglin/MixGCF/blob/main/utils/parser.py#L19).
3. Increase the number of using cores (https://github.com/huangtinglin/MixGCF/blob/main/utils/evaluate.py#L12).

**Comment by Coder-Yu** [comment]
I suggest the authors try numba to accelerate the evaluation
