### ISSUE TITLE
Number of negatives

### ISSUE THREAD

**Issue by TedSIWEILIU** [huangtinglin/MixGCF#4]
Hi, I have noticed that the provided configs all have K==1. However, in the paper, it's claimed that "Note that when 𝐾 = 1, the 𝐾-pair loss will degenerate into the BPR loss." 

I am not sure if that means the reported configs are not the best performing configs and shall we expect higher performance if I increase K.

**Comment by huangtinglin** [comment]
Sorry for the late reply! Actually, K=1 is the most common setting in related research. Thus we mainly compare MixGCF with other baselines under K=1. You can check some experimental results about the influence of K in the paper.

**Comment by TedSIWEILIU** [comment]
Ok, thanks very much for your help.
